# Generated by Django 5.2.1 on 2025-05-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_farm_certifications_user_farm_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farm_certifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farm_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='farming_specialties',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_of_experience',
        ),
    ]
